#!/bin/bash

set -a

HOME_DIR="$(dirname "$0")"

source "$HOME_DIR/.env"
if [ -f "$PWD/kubesh.env" ]; then
    source "$PWD/kubesh.env"
fi

# Load .env from the calling directory
if [ ! -f "$PWD/$DOT_ENV" ]; then
    echo "'$PWD/$DOT_ENV' not found!"
    exit
fi
source "$PWD/$DOT_ENV"

# Merge docker, minikube abd kube environments into one
MINIKUBE_AND_KUBE_ENVIRONMENTS=( "${MINIKUBE_ENVIRONMENTS[@]}" "${KUBE_ENVIRONMENTS[@]}" )
ALL_ENVIRONMENTS=( "${DOCKER_ENVIRONMENTS[@]}" "${MINIKUBE_AND_KUBE_ENVIRONMENTS[@]}" )
# Evaluate all environments
for i in "${ALL_ENVIRONMENTS[@]}"
do
	eval $i
done

source "$HOME_DIR/scripts/variables.env"
source "$HOME_DIR/scripts/common.sh"
source "$HOME_DIR/scripts/build.sh"
source "$HOME_DIR/scripts/run.sh"
source "$HOME_DIR/scripts/stop.sh"
source "$HOME_DIR/scripts/ssh.sh"
source "$HOME_DIR/scripts/log.sh"
source "$HOME_DIR/scripts/ls.sh"
source "$HOME_DIR/scripts/url.sh"
source "$HOME_DIR/scripts/docker.sh"
source "$HOME_DIR/scripts/gcloud.sh"
source "$HOME_DIR/scripts/kubernetes.sh"
source "$HOME_DIR/scripts/main.sh"

usage