#!/bin/bash
root_directory=$PWD

# Build Linux executable
docker build -t kubesh_builder_image .
docker run -it --rm --name kubesh_builder -v "$PWD/dist":/usr/src/app/dist kubesh_builder_image
cp helper/install_linux dist/install
cp kubesh.json dist/kubesh.json
cd $PWD/dist
tar -zcvf kubesh_linux.tar install kubesh kubesh.json
cd $root_directory

# Build MacOS executable
virtualenv kubesh
source kubesh/bin/activate
pip3 install -r requirements.txt

pyinstaller --clean kubesh.spec
cp helper/install_mac dist/install
cp kubesh.json dist/kubesh.json
cd $PWD/dist
tar -zcvf kubesh_mac.tar install kubesh kubesh.json
cd $root_directory

deactivate